create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create type public.communication_provider as enum ('email', 'slack', 'whatsapp');
create type public.message_direction as enum ('inbound', 'outbound', 'note', 'system');
create type public.message_delivery_status as enum ('queued', 'scheduled', 'sent', 'delivered', 'read', 'failed');
create type public.workspace_role as enum ('owner', 'admin', 'member');

create table public.profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  full_name text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.workspaces (
  id bigint generated by default as identity primary key,
  name text not null default 'Personal workspace',
  created_by bigint not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.workspace_members (
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  user_id bigint not null references public.profiles(id) on delete cascade,
  role public.workspace_role not null default 'member',
  created_at timestamptz not null default now(),
  primary key (workspace_id, user_id)
);

create function public.is_workspace_member(target_workspace_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.workspace_members wm
    where wm.workspace_id = target_workspace_id
      and exists (
        select 1 from public.profiles p
        where p.id = wm.user_id and p.auth_user_id = auth.uid()
      )
  );
$$;

create function public.create_personal_workspace_for_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_workspace_id bigint;
  new_profile_id bigint;
begin
  insert into public.profiles (auth_user_id, full_name, avatar_url)
  values (
    new.id,
    nullif(new.raw_user_meta_data ->> 'full_name', ''),
    nullif(new.raw_user_meta_data ->> 'avatar_url', '')
  )
  on conflict (auth_user_id) do update
    set full_name = excluded.full_name,
        avatar_url = excluded.avatar_url,
        updated_at = now();

  select p.id into new_profile_id
  from public.profiles p
  where p.auth_user_id = new.id;

  insert into public.workspaces (name, created_by)
  values (
    coalesce(nullif(new.raw_user_meta_data ->> 'account_name', ''), 'Personal workspace'),
    new_profile_id
  )
  returning id into new_workspace_id;

  insert into public.workspace_members (workspace_id, user_id, role)
  values (new_workspace_id, new_profile_id, 'owner');

  return new;
end;
$$;

create trigger on_auth_user_created_create_workspace
  after insert on auth.users
  for each row execute function public.create_personal_workspace_for_new_user();

create table public.provider_connections (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  provider public.communication_provider not null,
  external_account_id text not null,
  display_name text,
  account_address text,
  status text not null default 'connected'
    check (status in ('connected', 'needs_reauthorization', 'disconnected', 'error')),
  scopes text[] not null default '{}',
  metadata jsonb not null default '{}',
  connected_by bigint not null references public.profiles(id) on delete restrict,
  connected_at timestamptz not null default now(),
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workspace_id, provider, external_account_id),
  unique (id, workspace_id),
  unique (id, workspace_id, provider)
);

comment on table public.provider_connections is
  'Safe connection metadata only. OAuth tokens and provider secrets must live in Supabase Vault, never in this client-readable table.';

create table public.contacts (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  provider_connection_id bigint not null,
  external_id text not null,
  display_name text,
  handle text,
  avatar_url text,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider_connection_id, external_id),
  unique (id, workspace_id),
  foreign key (provider_connection_id, workspace_id)
    references public.provider_connections(id, workspace_id) on delete cascade
);

create table public.conversations (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  provider_connection_id bigint not null,
  contact_id bigint not null,
  provider public.communication_provider not null,
  external_id text not null,
  subject text,
  status text not null default 'open' check (status in ('open', 'pending', 'resolved', 'snoozed')),
  snoozed_until timestamptz,
  check ((status = 'snoozed') = (snoozed_until is not null)),
  unread_count integer not null default 0 check (unread_count >= 0),
  last_message_at timestamptz not null default now(),
  last_message_preview text not null default '',
  assigned_to bigint references public.profiles(id) on delete set null,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider_connection_id, external_id),
  foreign key (contact_id, workspace_id)
    references public.contacts(id, workspace_id) on delete cascade,
  foreign key (provider_connection_id, workspace_id)
    references public.provider_connections(id, workspace_id, provider) on delete cascade,
  unique (id, workspace_id)
);

create index conversations_workspace_activity_idx
  on public.conversations (workspace_id, last_message_at desc);
create index conversations_workspace_status_idx
  on public.conversations (workspace_id, status, last_message_at desc);
create index conversations_workspace_assignee_idx
  on public.conversations (workspace_id, assigned_to, last_message_at desc);

create table public.messages (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  provider_connection_id bigint not null,
  conversation_id bigint not null,
  external_id text,
  client_request_id uuid,
  direction public.message_direction not null,
  content text not null default '',
  content_html text,
  author_user_id bigint references public.profiles(id) on delete set null,
  author_name text,
  delivery_status public.message_delivery_status,
  delivery_error text,
  sent_at timestamptz,
  scheduled_at timestamptz,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (conversation_id, workspace_id)
    references public.conversations(id, workspace_id) on delete cascade,
  foreign key (provider_connection_id, workspace_id)
    references public.provider_connections(id, workspace_id) on delete cascade,
  unique (conversation_id, client_request_id)
);

create unique index messages_provider_external_id_idx
  on public.messages (provider_connection_id, external_id)
  where external_id is not null;
create index messages_conversation_created_idx
  on public.messages (conversation_id, created_at desc);
create index messages_workspace_status_idx
  on public.messages (workspace_id, delivery_status, created_at)
  where direction = 'outbound';

create table public.outbox_jobs (
  id uuid primary key default gen_random_uuid(),
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  message_id bigint not null unique references public.messages(id) on delete cascade,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'sent', 'failed', 'cancelled')),
  available_at timestamptz not null default now(),
  attempts integer not null default 0 check (attempts >= 0),
  locked_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index outbox_due_jobs_idx on public.outbox_jobs (available_at, created_at)
  where status = 'pending';

create table public.quick_replies (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  shortcut text not null,
  title text not null,
  body text not null,
  created_by bigint not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workspace_id, shortcut)
);

create table public.automation_rules (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  name text not null,
  description text,
  active boolean not null default true,
  event_name text not null,
  execution_delay integer check (execution_delay is null or execution_delay > 0),
  conditions jsonb not null default '[]',
  actions jsonb not null default '[]',
  metadata jsonb not null default '{}',
  created_by bigint not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create function public.ingest_provider_message(
  p_provider_connection_id bigint,
  p_contact_external_id text,
  p_contact_handle text,
  p_contact_name text,
  p_avatar_url text,
  p_conversation_external_id text,
  p_subject text,
  p_message_external_id text,
  p_direction public.message_direction,
  p_content text,
  p_occurred_at timestamptz,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  connection_row public.provider_connections%rowtype;
  contact_row public.contacts%rowtype;
  conversation_row public.conversations%rowtype;
  message_row public.messages%rowtype;
  event_time timestamptz := coalesce(p_occurred_at, now());
  message_status public.message_delivery_status;
  message_preview text;
begin
  select pc.* into connection_row
  from public.provider_connections pc
  where pc.id = p_provider_connection_id;
  if not found then
    raise exception 'provider connection not found' using errcode = 'P0002';
  end if;
  if connection_row.status <> 'connected' then
    raise exception 'provider connection is not active' using errcode = '55000';
  end if;
  if p_contact_external_id is null or length(btrim(p_contact_external_id)) = 0 then
    raise exception 'contact external id is required' using errcode = '22023';
  end if;
  if p_conversation_external_id is null or length(btrim(p_conversation_external_id)) = 0 then
    raise exception 'conversation external id is required' using errcode = '22023';
  end if;
  if p_direction is null or p_direction not in ('inbound', 'outbound') then
    raise exception 'provider messages must be inbound or outbound' using errcode = '22023';
  end if;
  if p_content is null or length(p_content) > 50000 then
    raise exception 'message content exceeds 50000 characters' using errcode = '22023';
  end if;

  insert into public.contacts (
    workspace_id, provider_connection_id, external_id, handle, display_name, avatar_url
  ) values (
    connection_row.workspace_id,
    connection_row.id,
    p_contact_external_id,
    coalesce(nullif(btrim(p_contact_handle), ''), p_contact_external_id),
    nullif(btrim(p_contact_name), ''),
    p_avatar_url
  )
  on conflict (provider_connection_id, external_id) do update
    set handle = coalesce(nullif(excluded.handle, ''), public.contacts.handle),
        display_name = coalesce(excluded.display_name, public.contacts.display_name),
        avatar_url = coalesce(excluded.avatar_url, public.contacts.avatar_url),
        updated_at = now()
  returning * into contact_row;

  insert into public.conversations (
    workspace_id, provider_connection_id, contact_id, provider, external_id, subject,
    last_message_at, last_message_preview
  ) values (
    connection_row.workspace_id,
    connection_row.id,
    contact_row.id,
    connection_row.provider,
    p_conversation_external_id,
    p_subject,
    event_time,
    ''
  )
  on conflict (provider_connection_id, external_id) do update
    set subject = coalesce(excluded.subject, public.conversations.subject),
        updated_at = now()
  returning * into conversation_row;

  message_status := case
    when p_direction = 'outbound' then 'sent'::public.message_delivery_status
    else null
  end;

  if p_message_external_id is null then
    insert into public.messages (
      workspace_id, provider_connection_id, conversation_id, direction, content,
      author_name, delivery_status, sent_at, metadata, created_at
    ) values (
      connection_row.workspace_id, connection_row.id, conversation_row.id, p_direction,
      p_content,
      case when p_direction = 'outbound' then 'You'
        else coalesce(nullif(p_contact_name, ''), contact_row.handle) end,
      message_status, case when p_direction = 'outbound' then event_time else null end,
      coalesce(p_metadata, '{}'::jsonb), event_time
    ) returning * into message_row;
  else
    insert into public.messages (
      workspace_id, provider_connection_id, conversation_id, external_id, direction,
      content, author_name, delivery_status, sent_at, metadata, created_at
    ) values (
      connection_row.workspace_id, connection_row.id, conversation_row.id, p_message_external_id,
      p_direction, p_content,
      case when p_direction = 'outbound' then 'You'
        else coalesce(nullif(p_contact_name, ''), contact_row.handle) end,
      message_status, case when p_direction = 'outbound' then event_time else null end,
      coalesce(p_metadata, '{}'::jsonb), event_time
    )
    on conflict (provider_connection_id, external_id) where external_id is not null
      do nothing
    returning * into message_row;
  end if;

  if message_row.id is null then
    select m.* into message_row
    from public.messages m
    where m.provider_connection_id = connection_row.id
      and m.external_id = p_message_external_id;
    return jsonb_build_object(
      'conversation_id', conversation_row.id,
      'message_id', message_row.id,
      'duplicate', true
    );
  end if;

  message_preview := left(regexp_replace(
    coalesce(nullif(p_content, ''), '[attachment]'), '\s+', ' ', 'g'
  ), 180);

  update public.conversations
  set last_message_at = greatest(last_message_at, event_time),
      last_message_preview = case
        when event_time >= last_message_at then message_preview
        else last_message_preview
      end,
      unread_count = case
        when p_direction = 'inbound' then unread_count + 1
        else unread_count
      end,
      status = case
        when p_direction = 'inbound' and status in ('resolved', 'pending', 'snoozed') then 'open'
        else status
      end,
      snoozed_until = case
        when p_direction = 'inbound' then null
        else snoozed_until
      end,
      updated_at = now()
  where id = conversation_row.id;

  update public.provider_connections
  set last_synced_at = now(), updated_at = now()
  where id = connection_row.id;

  return jsonb_build_object(
    'conversation_id', conversation_row.id,
    'message_id', message_row.id,
    'duplicate', false
  );
end;
$$;

create function public.set_conversation_status(
  p_conversation_id bigint,
  p_status text,
  p_snoozed_until timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  conversation_row public.conversations%rowtype;
begin
  if current_user_id is null then
    raise exception 'authentication required' using errcode = '28000';
  end if;
  if p_status is null or p_status not in ('open', 'pending', 'resolved', 'snoozed') then
    raise exception 'status must be open, pending, resolved, or snoozed' using errcode = '22023';
  end if;
  if p_status = 'snoozed' and (p_snoozed_until is null or p_snoozed_until <= now()) then
    raise exception 'snoozed conversations require a future wake time' using errcode = '22023';
  end if;

  update public.conversations c
  set status = p_status,
      snoozed_until = case when p_status = 'snoozed' then p_snoozed_until else null end,
      updated_at = now()
  where c.id = p_conversation_id
    and public.is_workspace_member(c.workspace_id)
  returning c.* into conversation_row;

  if not found then
    raise exception 'conversation not found' using errcode = 'P0002';
  end if;

  return jsonb_build_object(
    'id', conversation_row.id,
    'status', conversation_row.status,
    'snoozed_until', conversation_row.snoozed_until,
    'updated_at', conversation_row.updated_at
  );
end;
$$;

create function public.enqueue_reply(
  p_conversation_id bigint,
  p_content text,
  p_client_request_id uuid,
  p_scheduled_at timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  current_profile_id bigint;
  conversation_row public.conversations%rowtype;
  message_row public.messages%rowtype;
  message_status public.message_delivery_status;
begin
  if current_user_id is null then
    raise exception 'authentication required' using errcode = '28000';
  end if;
  select p.id into current_profile_id
  from public.profiles p
  where p.auth_user_id = current_user_id;
  if current_profile_id is null then
    raise exception 'user profile not found' using errcode = '28000';
  end if;
  if p_content is null or length(btrim(p_content)) = 0 then
    raise exception 'reply content is required' using errcode = '22023';
  end if;
  if p_client_request_id is null then
    raise exception 'client request id is required' using errcode = '22023';
  end if;
  if length(p_content) > 50000 then
    raise exception 'reply exceeds 50000 characters' using errcode = '22023';
  end if;

  select c.* into conversation_row
  from public.conversations c
  join public.provider_connections pc
    on pc.id = c.provider_connection_id
   and pc.workspace_id = c.workspace_id
  where c.id = p_conversation_id
    and public.is_workspace_member(c.workspace_id)
  for update;

  if not found then
    raise exception 'conversation not found' using errcode = 'P0002';
  end if;
  if conversation_row.status = 'resolved' then
    raise exception 'resolved conversations cannot receive replies' using errcode = '22023';
  end if;
  if not exists (
    select 1 from public.provider_connections pc
    where pc.id = conversation_row.provider_connection_id
      and pc.status = 'connected'
  ) then
    raise exception 'provider connection is not active' using errcode = '55000';
  end if;

  message_status := case
    when p_scheduled_at is not null and p_scheduled_at > now() then 'scheduled'::public.message_delivery_status
    else 'queued'::public.message_delivery_status
  end;

  insert into public.messages (
    workspace_id, provider_connection_id, conversation_id, client_request_id,
    direction, content, author_user_id, author_name, delivery_status, scheduled_at
  ) values (
    conversation_row.workspace_id,
    conversation_row.provider_connection_id,
    conversation_row.id,
    p_client_request_id,
    'outbound',
    p_content,
    current_profile_id,
    (select p.full_name from public.profiles p where p.id = current_profile_id),
    message_status,
    p_scheduled_at
  )
  on conflict (conversation_id, client_request_id) do nothing
  returning * into message_row;

  if message_row.id is null then
    select m.* into message_row
    from public.messages m
    where m.conversation_id = p_conversation_id
      and m.client_request_id = p_client_request_id;
    if message_row.id is null or message_row.direction <> 'outbound' then
      raise exception 'request id conflicts with another message' using errcode = '23505';
    end if;
    return jsonb_build_object(
      'id', message_row.id,
      'conversation_id', message_row.conversation_id,
      'inbox_id', conversation_row.provider_connection_id,
      'content', message_row.content,
      'author_user_id', message_row.author_user_id,
      'author_name', message_row.author_name,
      'delivery_status', message_row.delivery_status,
      'created_at', message_row.created_at,
      'duplicate', true
    );
  end if;

  insert into public.outbox_jobs (workspace_id, message_id, available_at)
  values (
    message_row.workspace_id,
    message_row.id,
    coalesce(p_scheduled_at, now())
  );

  update public.conversations
  set last_message_at = case
        when message_status = 'queued' then now()
        else last_message_at
      end,
      last_message_preview = case
        when message_status = 'queued' then left(regexp_replace(p_content, '\s+', ' ', 'g'), 180)
        else last_message_preview
      end,
      updated_at = now()
  where id = conversation_row.id;

  return jsonb_build_object(
    'id', message_row.id,
    'conversation_id', message_row.conversation_id,
    'inbox_id', conversation_row.provider_connection_id,
    'content', message_row.content,
    'author_user_id', message_row.author_user_id,
    'author_name', message_row.author_name,
    'delivery_status', message_row.delivery_status,
    'created_at', message_row.created_at,
    'duplicate', false
  );
end;
$$;

alter table public.profiles enable row level security;
alter table public.workspaces enable row level security;
alter table public.workspace_members enable row level security;
alter table public.provider_connections enable row level security;
alter table public.contacts enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.outbox_jobs enable row level security;
alter table public.quick_replies enable row level security;
alter table public.automation_rules enable row level security;

create policy profiles_select_self on public.profiles
  for select to authenticated using (auth_user_id = auth.uid());
create policy profiles_select_workspace_member on public.profiles
  for select to authenticated using (
    exists (
      select 1 from public.workspace_members wm
      where wm.user_id = profiles.id
        and public.is_workspace_member(wm.workspace_id)
    )
  );
create policy profiles_update_self on public.profiles
  for update to authenticated using (auth_user_id = auth.uid())
  with check (auth_user_id = auth.uid());

create policy workspaces_select_member on public.workspaces
  for select to authenticated using (public.is_workspace_member(id));
create policy workspaces_update_member on public.workspaces
  for update to authenticated using (public.is_workspace_member(id)) with check (public.is_workspace_member(id));

create policy workspace_members_select_member on public.workspace_members
  for select to authenticated using (public.is_workspace_member(workspace_id));

create policy provider_connections_select_member on public.provider_connections
  for select to authenticated using (public.is_workspace_member(workspace_id));
create policy contacts_select_workspace on public.contacts
  for select to authenticated using (public.is_workspace_member(workspace_id));
create policy conversations_select_workspace on public.conversations
  for select to authenticated using (public.is_workspace_member(workspace_id));
create policy messages_select_workspace on public.messages
  for select to authenticated using (public.is_workspace_member(workspace_id));
create policy quick_replies_select_member on public.quick_replies
  for select to authenticated using (public.is_workspace_member(workspace_id));
create policy quick_replies_insert_member on public.quick_replies
  for insert to authenticated with check (
    public.is_workspace_member(workspace_id)
    and created_by = (select p.id from public.profiles p where p.auth_user_id = auth.uid())
  );
create policy quick_replies_update_member on public.quick_replies
  for update to authenticated using (public.is_workspace_member(workspace_id))
  with check (public.is_workspace_member(workspace_id));
create policy quick_replies_delete_member on public.quick_replies
  for delete to authenticated using (public.is_workspace_member(workspace_id));
create policy automation_rules_select_member on public.automation_rules
  for select to authenticated using (public.is_workspace_member(workspace_id));
create policy automation_rules_insert_member on public.automation_rules
  for insert to authenticated with check (
    public.is_workspace_member(workspace_id)
    and created_by = (select p.id from public.profiles p where p.auth_user_id = auth.uid())
  );
create policy automation_rules_update_member on public.automation_rules
  for update to authenticated using (public.is_workspace_member(workspace_id))
  with check (public.is_workspace_member(workspace_id));
create policy automation_rules_delete_member on public.automation_rules
  for delete to authenticated using (public.is_workspace_member(workspace_id));

grant usage on schema public to authenticated, service_role;
grant select, update on public.profiles to authenticated;
grant select, update on public.workspaces to authenticated;
grant select on public.workspace_members to authenticated;
grant select on public.provider_connections to authenticated;
grant select on public.contacts, public.conversations to authenticated;
grant select on public.messages to authenticated;
grant select, insert, update, delete on public.quick_replies, public.automation_rules to authenticated;
grant all on public.outbox_jobs to service_role;
grant all on all tables in schema public to service_role;
grant execute on function public.is_workspace_member(bigint) to authenticated, service_role;
grant execute on function public.set_conversation_status(bigint, text, timestamptz) to authenticated;
grant execute on function public.enqueue_reply(bigint, text, uuid, timestamptz) to authenticated;
grant execute on function public.ingest_provider_message(
  bigint, text, text, text, text, text, text, text,
  public.message_direction, text, timestamptz, jsonb
) to service_role;

revoke all on function public.create_personal_workspace_for_new_user() from public, anon, authenticated;
revoke all on function public.is_workspace_member(bigint) from public, anon;
revoke all on function public.set_conversation_status(bigint, text, timestamptz) from public, anon;
revoke all on function public.enqueue_reply(bigint, text, uuid, timestamptz) from public, anon;
revoke all on function public.ingest_provider_message(
  bigint, text, text, text, text, text, text, text,
  public.message_direction, text, timestamptz, jsonb
) from public, anon, authenticated;
